apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s
  namespace: bermtec
  labels:
    app: docker-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-node
  template:
    metadata:
      labels:
        app: docker-node
    spec:
      containers:
      - name: k8s
        image: dockeravan/dockeravan/k8s:v1
        ports:
        - containerPort: 80