apiVersion: v1
kind: Service
metadata:
  name: docker-node
  namespace: bermtec
spec:
  selector: 
    app: docker-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
